version: '3'
services:
  counter:
    build: ../backend
    volumes:
      - ../backend:/app
    environment:
      REDIS_HOST: redis

  frontend:
    build: ../frontend
    ports:
      - 8080:80
    volumes:
      - ../frontend/src:/webapp

  redis:
    image: redis:5-alpine

