version: '3'
services:
  counter:
    image: aleskandro/pycounternginx:latest
    environment:
      REDIS_HOST: redis

  frontend:
    image: alexlocastro/pycounternginxapigw:latest
    ports:
      - 8080:80
  redis:
    image: redis:5-alpine
